---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openunison-operator
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openunison-operator-role
rules:
- apiGroups:
  - openunison.tremolo.io
  - ""
  - apps
  - rbac.authorization.k8s.io
  - extensions
  resources:
  - openunisons
  - pods
  - deployments
  - secrets
  - configmaps
  - services
  - serviceaccounts
  - roles
  - rolebindings
  - ingresses
  verbs:
  - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openunison-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: openunison-operator
  apiGroup: ""
roleRef:
  kind: Role
  name: openunison-operator-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openunison-operator-clusterrole
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openunison-operator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: openunison-operator
  namespace: openunison
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: openunison-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
